### ISSUE TITLE
csv to hdf5 converter missing

### ISSUE THREAD

**Issue by jainvishudh** [progirep/planet#3]
The script "build_database.sh"  in "planet/casestudies/vehicleCollision/" contains line -->
"  ../../tools/csv_to_hdf5_supervised_classification.py collisions.csv collisions.hdf5 "

But in tools directory the file "csv_to_hdf5_supervised_classification.py" seems to be missing.

**Comment by progirep** [comment]
That particular script is not part of this repository, but can be obtained in the way described in the "Preparation" section of the README.md file. The reason is that it is a modified "Github gist" script of another Github user. For copyright reasons, I cannot simply integrate it into this repository but kept it as a forked Github gist to circumvent this issue. Hence the necessity to execute the respective line in the README.md section.
